from DB.creation.db_creation import db_connection

from UI.popup import info_popup


def insert_hospital(hospital_data):

    connection = db_connection()

    cursor = connection.cursor()
    cursor.execute("USE autogenerated_blood_donation;")

    # hospital_data = [
    #     (12345, 'KCT Hospital', 'Password1@', 400, 50, 1234567890, 'Athipalayam', 'Saravanampatti', 'Coimbatore', 'Tamil Nadu', 'India',  2, 7, 9, 13,   37, 23, 32, 10,   50, 50, 50, 50,   50, 50, 50, 50),
    # ]

    hospital_data_insert_query = """
        INSERT INTO hospital (hid, hname, password, total_capacity, quantity_required, contact_no, street_name, city, district, state, country, o_plus_available, a_plus_available, b_plus_available, ab_plus_available, o_minus_available, a_minus_available, b_minus_available, ab_minus_available, o_plus_maximum, a_plus_maximum, b_plus_maximum, ab_plus_maximum, o_minus_maximum, a_minus_maximum, b_minus_maximum, ab_minus_maximum)
        VALUES (              %s ,%s    ,%s       ,%s             ,%s                ,%s         ,%s          ,%s   ,%s       ,%s    ,%s      ,%s               ,%s               ,%s               ,%s                ,%s               ,%s                 ,%s                ,%s                 ,%s             ,%s             ,%s             ,%s              ,%s              ,%s              ,%s              ,%s);
    """

    cursor.execute(hospital_data_insert_query,hospital_data)

    connection.commit()

    info_popup("Hospital data inserted successfully!")

    # Close the cursor and the connection
    cursor.close()
    connection.close()
