from DB.creation.db_creation import db_connection
import tkinter as tk

def admin_table_display():
    root = tk.Tk()
    root.geometry("400x250")

    connection = db_connection()
    cursor = connection.cursor()

    cursor.execute("USE autogenerated_blood_donation;")
    cursor.execute("SELECT admin_name, admin_id, password from admin limit 0,10;")

    # Create a canvas widget to hold the table
    canvas = tk.Canvas(root)
    canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

    # Create a frame to hold the table
    table_frame = tk.Frame(canvas)
    table_frame.pack(side=tk.TOP, fill=tk.BOTH, expand=True)

    h1 = tk.Label(table_frame,text="Admin_name")
    h1.grid(row=0,column=0)

    h2 = tk.Label(table_frame,text="Admin_id")
    h2.grid(row=0,column=1)

    h3 = tk.Label(table_frame,text="Password")
    h3.grid(row=0,column=2)

    # Add the table to the frame
    i = 1
    for trow in cursor:
        for j in range(len(trow)):
            e = tk.Label(table_frame, text=trow[j], width=10, fg='blue', borderwidth=2, relief='ridge', anchor="w")
            e.grid(row=i, column=j)
        i = i + 1

    # Add a horizontal scrollbar to the canvas
    scrollbar = tk.Scrollbar(canvas, orient=tk.HORIZONTAL, command=canvas.xview)
    scrollbar.pack(side=tk.BOTTOM, fill=tk.X)
    canvas.configure(xscrollcommand=scrollbar.set)

    # Configure the canvas to resize with the window
    table_frame.bind("<Configure>", lambda event: canvas.configure(scrollregion=canvas.bbox("all")))
    canvas.create_window((0, 0), window=table_frame, anchor='nw')

    root.mainloop()
