from DB.creation.db_creation import db_creation_connection

def create_db_table():

    connection = db_creation_connection()

    database_name = 'autogenerated_blood_donation'
    cursor = connection.cursor()
    # Check if the database exists and if not, create it
    cursor.execute("SHOW DATABASES LIKE '{}'".format(database_name)) 
    database_exists = cursor.fetchone()

    if not database_exists:
        cursor.execute("CREATE DATABASE {}".format(database_name))
        print("Database created successfully!")

    cursor.execute("USE autogenerated_blood_donation;")

    cursor.execute("SHOW TABLES LIKE 'hospital'")
    hospital_exists = cursor.fetchone()

    if not hospital_exists:
        cursor.execute(
            """ CREATE TABLE hospital (
                    hid INT NOT NULL ,
                    hname VARCHAR(30) NOT NULL,
                    password VARCHAR(30) NOT NULL,
                    total_capacity INT NOT NULL,
                    quantity_required INT NOT NULL,
                    contact_no BIGINT NOT NULL,
                    street_name VARCHAR(50) NOT NULL,
                    city VARCHAR(30) NOT NULL,
                    district VARCHAR(30) NOT NULL,
                    state VARCHAR(30) NOT NULL,
                    country VARCHAR(30) NOT NULL,
                    o_plus_available INT NOT NULL,
                    a_plus_available INT NOT NULL,
                    b_plus_available INT NOT NULL,
                    ab_plus_available INT NOT NULL,
                    o_minus_available INT NOT NULL,
                    a_minus_available INT NOT NULL,
                    b_minus_available INT NOT NULL,
                    ab_minus_available INT NOT NULL,
                    o_plus_maximum INT NOT NULL,
                    a_plus_maximum INT NOT NULL,
                    b_plus_maximum INT NOT NULL,
                    ab_plus_maximum INT NOT NULL,
                    o_minus_maximum INT NOT NULL,
                    a_minus_maximum INT NOT NULL,
                    b_minus_maximum INT NOT NULL,
                    ab_minus_maximum INT NOT NULL,
                    PRIMARY KEY (hid)
                    );
            """ 
        )
        print("Hospital table created successfully!")

        hospital_data = [
            (12345, 'KCT Hospital', 'Password1@', 400, 50, 1234567890, 'Athipalayam', 'Saravanampatti', 'Coimbatore', 'Tamil Nadu', 'India',  2, 7, 9, 13,   37, 23, 32, 10,   50, 50, 50, 50,   50, 50, 50, 50),
        ]

        hospital_data_insert_query = """
            INSERT INTO hospital (hid, hname, password, total_capacity, quantity_required, contact_no, street_name, city, district, state, country, o_plus_available, a_plus_available, b_plus_available, ab_plus_available, o_minus_available, a_minus_available, b_minus_available, ab_minus_available, o_plus_maximum, a_plus_maximum, b_plus_maximum, ab_plus_maximum, o_minus_maximum, a_minus_maximum, b_minus_maximum, ab_minus_maximum)
            VALUES (              %s ,%s    ,%s       ,%s             ,%s                ,%s         ,%s          ,%s   ,%s       ,%s    ,%s      ,%s               ,%s               ,%s               ,%s                ,%s               ,%s                 ,%s                ,%s                 ,%s             ,%s             ,%s             ,%s              ,%s              ,%s              ,%s              ,%s);
        """

        cursor.executemany(hospital_data_insert_query,hospital_data)

        connection.commit()

        print("Hospital data inserted successfully!")




    # Check if the table exists
    cursor.execute("SHOW TABLES LIKE 'donor'")
    donor_exists = cursor.fetchone()

    if not donor_exists:
        cursor.execute(
            """ CREATE TABLE donor (
                    aadhaar_id bigint NOT NULL PRIMARY KEY,
                    gender varchar(30) NOT NULL,
                    first_name varchar(30) NOT NULL,
                    last_name varchar(30),
                    dob INT NOT NULL,
                    mob INT NOT NULL,
                    yob INT NOT NULL,
                    blood_type varchar(3) NOT NULL,
                    pregnancy_status BOOL NOT NULL,
                    HIV BOOL NOT NULL,
                    street varchar(30) NOT NULL,
                    city varchar(30) NOT NULL,
                    district varchar(30) NOT NULL,
                    state varchar(30) NOT NULL,
                    country varchar(30) NOT NULL,
                    country_code varchar(3) NOT NULL,
                    password varchar(30) NOT NULL,
                    father_name varchar(30),
                    mother_name varchar(30),
                    gaurdian_name varchar(30),
                    ph1 bigint NOT NULL,
                    ph2 bigint,
                    hid int NOT NULL,
                    FOREIGN KEY ( hid) REFERENCES hospital(hid)
                );
            """ 
        )
        print("Donor table created successfully!")


    cursor.execute("SHOW TABLES LIKE 'admin'")
    admin_exists = cursor.fetchone()

    if not admin_exists:
        cursor.execute(
            """ 
                CREATE TABLE admin (
                    admin_name varchar(50),
                    admin_id INT NOT NULL,
                    password VARCHAR(30) NOT NULL,
                    PRIMARY KEY (admin_id)
                    );
            """ 
        )
        print("Admin table created successfully!")

        admin_data = [
            ('Admin', 1234, 'AAAA'),
        ]

        admin_data_insert_query = """
            INSERT INTO admin (admin_name, admin_id, password)
            VALUES (            %s        ,%s       ,%s);
        """

        cursor.executemany(admin_data_insert_query,admin_data)

        connection.commit()

        print("Admin data inserted successfully!")

    cursor.execute("SHOW TABLES LIKE 'reports'")
    reports_exists = cursor.fetchone()

    if not reports_exists:
        cursor.execute(
            """ 
                CREATE TABLE reports (
                    date DATE NOT NULL,
                    time TIME NOT NULL,
                    no_units_donated INT NOT NULL,
                    hid INT NOT NULL, 
                    aadhaar_id bigint NOT NULL,
                    FOREIGN KEY (aadhaar_id) REFERENCES donor(aadhaar_id),
                    FOREIGN KEY (hid) REFERENCES hospital(hid)
                    );
            """
        )
        print("Reports table created successfully!") 
        
    # cursor.execute("USE autogenerated_blood_donation;")
